// GT7 Parts Shop Data
// Source: gt7data/gt7_parts_shop.csv
// 72 parts across 5 categories
// Generated by scripts/generate-parts-shop.ts

export interface PartShopCategory {
  name: string;
  parts: string[];
}

export const PARTS_SHOP_DATA: PartShopCategory[] = [
  {
    name: "Sports",
    parts: [
      "Sports Computer",
      "Sports Air Filter",
      "Sports Silencer",
      "Sports Brake Pads",
      "Street Suspension",
      "Weight Reduction: Stage 1",
      "Comfort: Hard",
      "Comfort: Medium",
      "Comfort: Soft",
      "Sports: Hard",
      "Sports: Medium",
      "Sports: Soft",
    ],
  },
  {
    name: "Club Sports",
    parts: [
      "Bore Up",
      "High Lift Camshaft",
      "High Compression Pistons",
      "Sports Suspension",
      "Sports Brake Kit",
      "Sports Clutch and Flywheel",
      "One-Way LSD",
      "Two-Way LSD",
      "Close-Ratio Transmission - Low",
      "Close-Ratio Transmission - High",
      "Weight Reduction: Stage 2",
      "Power Restrictor",
      "Ballast",
      "Dirt",
    ],
  },
  {
    name: "Semi-Racing",
    parts: [
      "Racing Crank Shaft",
      "Fully Customisable Computer",
      "Semi-Racing Silencer",
      "Low-RPM Turbocharger",
      "Medium-RPM Turbocharger",
      "High-RPM Turbocharger",
      "Supercharger: Low-End Torque",
      "Sports Intercooler",
      "Height-Adjustable Sports Suspension",
      "Semi-Racing Clutch and Flywheel",
      "Fully Customisable LSD",
      "Fully Customisable Manual Transmission",
      "Weight Reduction: Stage 3",
      "Increase Body Rigidity",
    ],
  },
  {
    name: "Racing",
    parts: [
      "Stroke Up",
      "Engine Balance Tuning",
      "Polish Ports",
      "Anti-Lag System",
      "Supercharger: High-End Torque",
      "Racing Intercooler",
      "Racing Air Filter",
      "Racing Silencer",
      "Racing Brake Kit (Slotted)",
      "Racing Brake Kit (Drilled)",
      "Race Brake Pads",
      "Brake Balance Controller",
      "Race Manifold",
      "Fully Customisable Suspension",
      "Racing Clutch and Flywheel",
      "Torque-Vectoring Centre Differential",
      "Active LSD Controller",
      "Fully Customisable Racing Transmission",
      "Weight Reduction: Stage 4",
      "Racing: Hard",
      "Racing: Medium",
      "Racing: Soft",
    ],
  },
  {
    name: "Extreme",
    parts: [
      "Nitrous System",
      "Carbon Ceramic Brake Kit",
      "Hydraulic Handbrake",
      "Steering Angle Adapter",
      "Four-Wheel Steering Controller",
      "Snow Tyres",
      "Intermediate",
      "Racing: Heavy Wet",
      "New Engine",
      "New Body",
    ],
  },
];

// Helper to get all unique part names
export const ALL_PARTS = PARTS_SHOP_DATA.flatMap((category) =>
  category.parts,
);

// Helper to get category for a specific part
export function getPartCategory(partName: string): string | undefined {
  for (const category of PARTS_SHOP_DATA) {
    if (category.parts.includes(partName)) {
      return category.name;
    }
  }
  return undefined;
}
