-- ROLLBACK: Drop gear columns from CarBuild (if migration needs to be reverted)
-- WARNING: This will DELETE all migrated gear data from CarBuild columns!
-- Only run this if you need to rollback the migration

-- First, you'll need to restore data from CarBuildSetting if you already ran cleanup
-- If you haven't run cleanup yet, the data is still in CarBuildSetting

-- Uncomment to drop the columns
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "finalDrive";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear1";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear2";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear3";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear4";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear5";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear6";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear7";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear8";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear9";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear10";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear11";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear12";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear13";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear14";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear15";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear16";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear17";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear18";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear19";
-- ALTER TABLE "CarBuild" DROP COLUMN IF EXISTS "gear20";
