#!/usr/bin/env node
/**
 * Generate parts-shop.ts from gt7_parts_shop.csv
 * Run this script after adding new parts to the CSV file
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CSV_PATH = path.join(__dirname, '../gt7data/gt7_parts_shop.csv');
const OUTPUT_PATH = path.join(__dirname, '../src/data/builds/parts-shop.ts');

interface PartShopCategory {
  name: string;
  parts: string[];
}

function parseCSV(filePath: string): PartShopCategory[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n').filter(line => line.trim());

  // Skip header row
  const dataLines = lines.slice(1);

  const categoriesMap = new Map<string, string[]>();

  for (const line of dataLines) {
    // Split by comma, but handle quoted strings if any
    const match = line.match(/^([^,]+),(.+)$/);
    if (!match) continue;

    const [, category, part] = match;
    const trimmedPart = part.trim();

    if (!trimmedPart) continue; // Skip empty parts

    if (!categoriesMap.has(category)) {
      categoriesMap.set(category, []);
    }

    categoriesMap.get(category)!.push(trimmedPart);
  }

  // Convert map to array and maintain order
  const categoryOrder = ['Sports', 'Club Sports', 'Semi-Racing', 'Racing', 'Extreme'];
  const categories: PartShopCategory[] = [];

  for (const categoryName of categoryOrder) {
    const parts = categoriesMap.get(categoryName);
    if (parts && parts.length > 0) {
      categories.push({ name: categoryName, parts });
    }
  }

  // Add any remaining categories not in the predefined order
  for (const [categoryName, parts] of categoriesMap.entries()) {
    if (!categoryOrder.includes(categoryName)) {
      categories.push({ name: categoryName, parts });
    }
  }

  return categories;
}

function countTotalParts(categories: PartShopCategory[]): number {
  return categories.reduce((sum, cat) => sum + cat.parts.length, 0);
}

function generateTypeScriptFile(categories: PartShopCategory[]): string {
  const totalParts = countTotalParts(categories);
  const totalCategories = categories.length;

  let output = `// GT7 Parts Shop Data\n`;
  output += `// Source: gt7data/gt7_parts_shop.csv\n`;
  output += `// ${totalParts} parts across ${totalCategories} categories\n`;
  output += `// Generated by scripts/generate-parts-shop.ts\n\n`;

  output += `export interface PartShopCategory {\n`;
  output += `  name: string;\n`;
  output += `  parts: string[];\n`;
  output += `}\n\n`;

  output += `export const PARTS_SHOP_DATA: PartShopCategory[] = [\n`;

  for (const category of categories) {
    output += `  {\n`;
    output += `    name: "${category.name}",\n`;
    output += `    parts: [\n`;

    for (const part of category.parts) {
      // Escape quotes in part names
      const escapedPart = part.replace(/"/g, '\\"');
      output += `      "${escapedPart}",\n`;
    }

    output += `    ],\n`;
    output += `  },\n`;
  }

  output += `];\n\n`;

  // Helper functions
  output += `// Helper to get all unique part names\n`;
  output += `export const ALL_PARTS = PARTS_SHOP_DATA.flatMap((category) =>\n`;
  output += `  category.parts,\n`;
  output += `);\n\n`;

  output += `// Helper to get category for a specific part\n`;
  output += `export function getPartCategory(partName: string): string | undefined {\n`;
  output += `  for (const category of PARTS_SHOP_DATA) {\n`;
  output += `    if (category.parts.includes(partName)) {\n`;
  output += `      return category.name;\n`;
  output += `    }\n`;
  output += `  }\n`;
  output += `  return undefined;\n`;
  output += `}\n`;

  return output;
}

function main() {
  console.log('🔧 Reading CSV file...');
  const categories = parseCSV(CSV_PATH);

  console.log(`📊 Found ${categories.length} categories with ${countTotalParts(categories)} total parts`);

  console.log('📝 Generating TypeScript file...');
  const tsContent = generateTypeScriptFile(categories);

  console.log(`💾 Writing to ${OUTPUT_PATH}...`);
  fs.writeFileSync(OUTPUT_PATH, tsContent, 'utf-8');

  console.log('✅ Done! parts-shop.ts has been updated.');
  console.log('');
  console.log('Summary:');
  for (const category of categories) {
    console.log(`  ${category.name}: ${category.parts.length} parts`);
  }
}

try {
  main();
} catch (error) {
  console.error('❌ Error:', error);
  process.exit(1);
}
