#!/usr/bin/env node
/**
 * Generate Parts Shop TypeScript Data File from CSV
 *
 * This script reads the GT7 parts shop CSV file and generates a TypeScript data file
 * that can be imported by the application. The generated file contains parts organized
 * by category with helper functions for accessing the data.
 *
 * Usage:
 *   npm run generate:parts
 *   OR
 *   npx tsx scripts/generate-parts-shop.ts
 *
 * Prerequisites:
 *   - GT7 parts shop CSV must exist at: gt7data/gt7_parts_shop.csv
 *   - CSV format: Category,Part columns
 *   - Output directory: src/data/builds/ (must exist)
 *
 * Data Flow:
 *   1. Read CSV file from gt7data/gt7_parts_shop.csv
 *   2. Parse CSV and group parts by category
 *   3. Order categories according to predefined hierarchy:
 *      - Sports, Club Sports, Semi-Racing, Racing, Extreme
 *      - Any additional categories appended after
 *   4. Generate TypeScript file with:
 *      - Interface definition (PartShopCategory)
 *      - Constant data array (PARTS_SHOP_DATA)
 *      - Helper functions (ALL_PARTS, getPartCategory)
 *   5. Write generated file to src/data/builds/parts-shop.ts
 *   6. Display summary of categories and part counts
 *
 * Error Handling:
 *   - Catches and reports file system errors
 *   - Exits with status code 1 on error
 *   - Skips empty lines and parts during parsing
 *   - Handles missing output directory gracefully
 *
 * Category Ordering:
 *   Categories are ordered to match the game's progression:
 *   1. Sports (entry-level parts)
 *   2. Club Sports (step up from sports)
 *   3. Semi-Racing (intermediate level)
 *   4. Racing (professional level)
 *   5. Extreme (highest performance)
 *   6. Any other categories found in CSV
 *
 * Generated File Structure:
 *   - Interface: PartShopCategory
 *     * name: string (category name)
 *     * parts: string[] (array of part names)
 *
 *   - Constant: PARTS_SHOP_DATA
 *     * Array of PartShopCategory objects
 *     * Exported for use in application
 *
 *   - Helper: ALL_PARTS
 *     * Flat array of all part names
 *     * Generated by flatMapping categories
 *
 *   - Helper: getPartCategory(partName: string)
 *     * Returns category name for a given part
 *     * Returns undefined if part not found
 *
 * CSV Parsing Details:
 *   - Simple comma-separated format
 *   - First row is header (skipped)
 *   - Empty lines are filtered out
 *   - Empty parts are skipped
 *   - Whitespace is trimmed from values
 *   - No quote handling (not needed for this data)
 *
 * Output File Features:
 *   - Header comment with source and stats
 *   - TypeScript interfaces for type safety
 *   - Escaped quotes in part names
 *   - Formatted with proper indentation
 *   - Helper functions for common queries
 *
 * File Paths:
 *   - Input: gt7data/gt7_parts_shop.csv
 *   - Output: src/data/builds/parts-shop.ts
 *
 * Important Notes:
 *   - Overwrites existing parts-shop.ts file
 *   - Script is idempotent (can be run multiple times)
 *   - Changes to CSV are immediately reflected in generated file
 *   - No database interaction (generates static data file)
 *   - Used for build creation UI components
 *
 * Example Generated Output:
 *   ```typescript
 *   export const PARTS_SHOP_DATA: PartShopCategory[] = [
 *     {
 *       name: "Sports",
 *       parts: ["Sports Computer", "Sports Exhaust", ...],
 *     },
 *     ...
 *   ];
 *
 *   export const ALL_PARTS = PARTS_SHOP_DATA.flatMap(c => c.parts);
 *
 *   export function getPartCategory(partName: string): string | undefined {
 *     // Implementation
 *   }
 *   ```
 *
 * Dependencies:
 *   - fs: File system access for reading CSV and writing output
 *   - path: Path manipulation for file locations
 *   - url/fileURLToPath: ESM compatibility for __dirname
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CSV_PATH = path.join(__dirname, '../gt7data/gt7_parts_shop.csv');
const OUTPUT_PATH = path.join(__dirname, '../src/data/builds/parts-shop.ts');

// ============================================================================
// Type Definitions
// ============================================================================

interface PartShopCategory {
  name: string;
  parts: string[];
}

// ============================================================================
// CSV Parser
// ============================================================================

/**
 * Parse parts shop CSV file and group parts by category
 * Filters empty rows and maintains category ordering
 *
 * @param filePath - Path to CSV file
 * @returns Array of categories with their parts
 */
function parseCSV(filePath: string): PartShopCategory[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n').filter(line => line.trim());

  // Skip header row
  const dataLines = lines.slice(1);

  const categoriesMap = new Map<string, string[]>();

  // Parse each line and group by category
  for (const line of dataLines) {
    // Split by comma, but handle quoted strings if any
    const match = line.match(/^([^,]+),(.+)$/);
    if (!match) continue;

    const [, category, part] = match;
    const trimmedPart = part.trim();

    // Skip empty parts
    if (!trimmedPart) continue;

    // Initialize category array if not exists
    if (!categoriesMap.has(category)) {
      categoriesMap.set(category, []);
    }

    // Add part to category
    categoriesMap.get(category)!.push(trimmedPart);
  }

  // Convert map to array and maintain order
  const categoryOrder = ['Sports', 'Club Sports', 'Semi-Racing', 'Racing', 'Extreme'];
  const categories: PartShopCategory[] = [];

  // Add categories in predefined order
  for (const categoryName of categoryOrder) {
    const parts = categoriesMap.get(categoryName);
    if (parts && parts.length > 0) {
      categories.push({ name: categoryName, parts });
    }
  }

  // Add any remaining categories not in the predefined order
  for (const [categoryName, parts] of categoriesMap.entries()) {
    if (!categoryOrder.includes(categoryName)) {
      categories.push({ name: categoryName, parts });
    }
  }

  return categories;
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Count total parts across all categories
 *
 * @param categories - Array of part categories
 * @returns Total number of parts
 */
function countTotalParts(categories: PartShopCategory[]): number {
  return categories.reduce((sum, cat) => sum + cat.parts.length, 0);
}

// ============================================================================
// TypeScript Code Generator
// ============================================================================

/**
 * Generate TypeScript file content from categories
 * Creates interfaces, constants, and helper functions
 *
 * @param categories - Array of part categories
 * @returns Complete TypeScript file content as string
 */
function generateTypeScriptFile(categories: PartShopCategory[]): string {
  const totalParts = countTotalParts(categories);
  const totalCategories = categories.length;

  // File header with metadata
  let output = `// GT7 Parts Shop Data\n`;
  output += `// Source: gt7data/gt7_parts_shop.csv\n`;
  output += `// ${totalParts} parts across ${totalCategories} categories\n`;
  output += `// Generated by scripts/generate-parts-shop.ts\n\n`;

  // Interface definition
  output += `export interface PartShopCategory {\n`;
  output += `  name: string;\n`;
  output += `  parts: string[];\n`;
  output += `}\n\n`;

  // Data constant
  output += `export const PARTS_SHOP_DATA: PartShopCategory[] = [\n`;

  // Add each category
  for (const category of categories) {
    output += `  {\n`;
    output += `    name: "${category.name}",\n`;
    output += `    parts: [\n`;

    // Add each part with quote escaping
    for (const part of category.parts) {
      // Escape quotes in part names
      const escapedPart = part.replace(/"/g, '\\"');
      output += `      "${escapedPart}",\n`;
    }

    output += `    ],\n`;
    output += `  },\n`;
  }

  output += `];\n\n`;

  // Helper function: Get all parts as flat array
  output += `// Helper to get all unique part names\n`;
  output += `export const ALL_PARTS = PARTS_SHOP_DATA.flatMap((category) =>\n`;
  output += `  category.parts,\n`;
  output += `);\n\n`;

  // Helper function: Get category for a specific part
  output += `// Helper to get category for a specific part\n`;
  output += `export function getPartCategory(partName: string): string | undefined {\n`;
  output += `  for (const category of PARTS_SHOP_DATA) {\n`;
  output += `    if (category.parts.includes(partName)) {\n`;
  output += `      return category.name;\n`;
  output += `    }\n`;
  output += `  }\n`;
  output += `  return undefined;\n`;
  output += `}\n`;

  return output;
}

// ============================================================================
// Main Execution
// ============================================================================

/**
 * Main function to orchestrate the generation process
 * Coordinates parsing, generation, and file writing
 */
function main() {
  console.log('🔧 Reading CSV file...');
  const categories = parseCSV(CSV_PATH);

  console.log(`📊 Found ${categories.length} categories with ${countTotalParts(categories)} total parts`);

  console.log('📝 Generating TypeScript file...');
  const tsContent = generateTypeScriptFile(categories);

  console.log(`💾 Writing to ${OUTPUT_PATH}...`);
  fs.writeFileSync(OUTPUT_PATH, tsContent, 'utf-8');

  console.log('✅ Done! parts-shop.ts has been updated.');
  console.log('');
  console.log('Summary:');
  // Display breakdown by category
  for (const category of categories) {
    console.log(`  ${category.name}: ${category.parts.length} parts`);
  }
}

// Execute with error handling
try {
  main();
} catch (error) {
  console.error('❌ Error:', error);
  process.exit(1);
}
